#!/usr/bin/env python3
"""
Verify all 129 matrix-generation branches in the canonical smoke manifest.
"""

from __future__ import annotations

import csv
import json
import math
import sys
from collections import Counter
from pathlib import Path

import numpy as np

from families import (
    build_matrix,
    diagonal_dominance_gap,
    infinity_norm,
    stable_matrix_id,
    stable_seed,
)


DD_FAMILIES = {
    "row_diagonal_dominant_random",
    "row_diagonal_dominant_tridiagonal",
    "row_diagonal_dominant_rankone",
    "row_diagonal_dominant_stochastic",
}


def fail(message: str) -> None:
    print(f"FAMILY_VERIFICATION_FAILED: {message}")
    sys.exit(1)


def main() -> None:
    manifest_path = Path(
        "reports/smoke/smoke_manifest.csv"
    )
    summary_path = Path(
        "reports/smoke/smoke_manifest_summary.json"
    )

    summary = json.loads(
        summary_path.read_text(encoding="utf-8")
    )

    seed_namespace = str(summary["seed_namespace"])

    rows = []

    with manifest_path.open(
        newline="",
        encoding="utf-8",
    ) as handle:
        rows.extend(csv.DictReader(handle))

    if len(rows) != 129:
        fail(f"expected 129 blocks, obtained {len(rows)}")

    families_seen = Counter()
    seeds = set()
    matrix_ids = set()

    stochastic_changed = 0
    deterministic_reproduced = 0
    dd_checked = 0
    spd_checked = 0
    orthogonal_checked = 0
    positive_checked = 0

    worst_dd_gap_error = 0.0
    worst_dd_norm_error = 0.0
    worst_spd_symmetry = 0.0
    worst_orthogonality = 0.0

    for row in rows:
        family = str(row["family"])
        n = int(row["n"])
        cell_id = str(row["cell_id"])
        stochastic = str(row["stochastic"]).lower() == "true"

        parameters = json.loads(row["parameters_json"])

        seed = stable_seed(
            seed_namespace=seed_namespace,
            cell_id=cell_id,
            n=n,
            replica=0,
        )
        matrix_id = stable_matrix_id(
            seed_namespace=seed_namespace,
            cell_id=cell_id,
            n=n,
            replica=0,
        )

        if seed in seeds:
            fail(f"duplicate 64-bit seed: {seed}")
        seeds.add(seed)

        if matrix_id in matrix_ids:
            fail(f"duplicate matrix_id: {matrix_id}")
        matrix_ids.add(matrix_id)

        a = build_matrix(
            family=family,
            n=n,
            parameters=parameters,
            seed=seed,
        )
        b = build_matrix(
            family=family,
            n=n,
            parameters=parameters,
            seed=seed,
        )

        if a.shape != (n, n):
            fail(
                f"wrong shape for {family}, cell={cell_id}: "
                f"{a.shape}"
            )

        if not np.array_equal(a, b, equal_nan=True):
            fail(
                f"non-reproducible matrix for {family}, "
                f"cell={cell_id}"
            )

        deterministic_reproduced += 1

        # The float64 reference generator itself must not create NaN.
        # Infinity may occur only in an explicitly extreme Kahan branch.
        if np.isnan(a).any():
            fail(
                f"NaN generated by {family}, parameters={parameters}"
            )

        if np.count_nonzero(a) == 0:
            fail(
                f"zero matrix generated by {family}, "
                f"parameters={parameters}"
            )

        if stochastic:
            seed_1 = stable_seed(
                seed_namespace=seed_namespace,
                cell_id=cell_id,
                n=n,
                replica=1,
            )
            a_1 = build_matrix(
                family=family,
                n=n,
                parameters=parameters,
                seed=seed_1,
            )

            if np.array_equal(a, a_1, equal_nan=True):
                fail(
                    f"stochastic cell produced identical replicas: "
                    f"{family}, {parameters}"
                )

            stochastic_changed += 1

        if family in DD_FAMILIES:
            if not np.all(np.isfinite(a)):
                fail(
                    f"nonfinite DD matrix: {family}, {parameters}"
                )

            requested_alpha = float(parameters["alpha"])
            measured_alpha = diagonal_dominance_gap(a)
            norm_inf = infinity_norm(a)

            gap_error = abs(measured_alpha - requested_alpha)
            norm_error = abs(norm_inf - 1.0)

            worst_dd_gap_error = max(
                worst_dd_gap_error,
                gap_error,
            )
            worst_dd_norm_error = max(
                worst_dd_norm_error,
                norm_error,
            )

            tolerance = (
                20000.0
                * np.finfo(np.float64).eps
                * max(1.0, abs(requested_alpha))
            )

            if gap_error > tolerance:
                fail(
                    f"wrong DD gap for {family}: "
                    f"requested={requested_alpha}, "
                    f"measured={measured_alpha}"
                )

            if norm_error > 20000.0 * np.finfo(np.float64).eps:
                fail(
                    f"wrong infinity norm for {family}: "
                    f"{norm_inf}"
                )

            dd_checked += 1

        if family == "spd_prescribed_spectrum":
            if not np.all(np.isfinite(a)):
                fail(f"nonfinite SPD matrix: {parameters}")

            symmetry_error = (
                np.linalg.norm(a - a.T)
                / max(np.linalg.norm(a), np.finfo(float).tiny)
            )
            worst_spd_symmetry = max(
                worst_spd_symmetry,
                float(symmetry_error),
            )

            eigenvalues = np.linalg.eigvalsh(a)

            if eigenvalues[0] <= 0.0:
                fail(
                    f"SPD matrix is not positive definite: "
                    f"{parameters}"
                )

            spd_checked += 1

        if family in {
            "adversarial_rotation",
            "repeated_bad_pivots",
        }:
            if not np.all(np.isfinite(a)):
                fail(
                    f"nonfinite orthogonal adversarial matrix: "
                    f"{family}, {parameters}"
                )

            defect = (
                np.linalg.norm(a.T @ a - np.eye(n))
                / math.sqrt(n)
            )
            worst_orthogonality = max(
                worst_orthogonality,
                float(defect),
            )

            if defect > 5000.0 * np.finfo(float).eps:
                fail(
                    f"orthogonality defect too large for "
                    f"{family}: {defect}"
                )

            orthogonal_checked += 1

        if family in {
            "tnn_vandermonde_positive",
            "pascal",
        }:
            if not np.all(np.isfinite(a)):
                fail(
                    f"nonfinite positive structured matrix: "
                    f"{family}, {parameters}"
                )

            if np.min(a) < 0.0:
                fail(
                    f"negative entry in positive structured family: "
                    f"{family}"
                )

            positive_checked += 1

        families_seen[family] += 1

    expected_families = set(summary["families"])

    if set(families_seen) != expected_families:
        fail(
            "family coverage mismatch: "
            f"seen={sorted(families_seen)}, "
            f"expected={sorted(expected_families)}"
        )

    if stochastic_changed != 64:
        fail(
            f"expected 64 stochastic branches, "
            f"verified {stochastic_changed}"
        )

    if dd_checked != 40:
        fail(
            f"expected 40 DD branches, verified {dd_checked}"
        )

    print("FAMILY_BRANCHES=129")
    print("FAMILIES=14")
    print(f"STOCHASTIC_BRANCHES={stochastic_changed}")
    print(f"DETERMINISTIC_REPRODUCTIONS={deterministic_reproduced}")
    print(f"DD_BRANCHES={dd_checked}")
    print(f"SPD_BRANCHES={spd_checked}")
    print(f"ORTHOGONAL_ADVERSARIAL_BRANCHES={orthogonal_checked}")
    print(f"POSITIVE_STRUCTURED_BRANCHES={positive_checked}")
    print(f"UNIQUE_SEEDS={len(seeds)}")
    print(f"UNIQUE_MATRIX_IDS={len(matrix_ids)}")
    print(f"WORST_DD_GAP_ERROR={worst_dd_gap_error:.16e}")
    print(f"WORST_DD_NORM_ERROR={worst_dd_norm_error:.16e}")
    print(f"WORST_SPD_SYMMETRY={worst_spd_symmetry:.16e}")
    print(f"WORST_ORTHOGONALITY={worst_orthogonality:.16e}")
    print("FAMILY_VERIFICATION_OK")


if __name__ == "__main__":
    main()
